Repository OpenDevUFCG/Tamburetei, pull requests merged in 2022-10, with the labels that each got.

#501 Update extras.md
  tc/extras.md
Labels: hacktoberfest, hacktoberfest-accepted

#505 Update README.md
  tc/leites/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#499 Criando pasta de Programação Concorrente e adicionando resumos
  prog_concorrente/README.md
  prog_concorrente/dificuldadesComuns.md
  prog_concorrente/extras.md
  prog_concorrente/linksUteis.md
  prog_concorrente/resumos/README.md
  prog_concorrente/resumos/assets_resumo_1/Captura_de_tela_de_2022-06-28_15-07-25.png
  prog_concorrente/resumos/assets_resumo_1/Captura_de_tela_de_2022-06-28_15-08-46.png
  prog_concorrente/resumos/assets_resumo_1/Untitled 1.png
  prog_concorrente/resumos/assets_resumo_1/Untitled 2.png
  prog_concorrente/resumos/assets_resumo_1/Untitled.png
  prog_concorrente/resumos/assets_resumo_2/2O6PF5M2PX7WCIBP.gif
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-21_17-08-08.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_08-19-00.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_08-24-48.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_08-37-26.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_08-44-59.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_08-55-48.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_09-03-43.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_09-06-52.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_09-08-25.png
  prog_concorrente/resumos/assets_resumo_2/Captura_de_tela_de_2022-07-25_09-11-38.png
  prog_concorrente/resumos/assets_resumo_2/KBJ9G60H38KQ0S73.gif
  prog_concorrente/resumos/assets_resumo_2/M2V5VN909F774S03_(1).gif
  prog_concorrente/resumos/assets_resumo_2/N4526UMP2TEO3PN9.gif
  prog_concorrente/resumos/assets_resumo_2/OP2J9UI2O7LPJFED_(1).gif
  prog_concorrente/resumos/assets_resumo_2/S9KAH0KTTT5J4UQ7.gif
  prog_concorrente/resumos/assets_resumo_2/YWU4FZUGQVFH98CZ.gif
  prog_concorrente/resumos/assets_resumo_3/Captura_de_tela_de_2022-06-28_15-07-25.png
  prog_concorrente/resumos/assets_resumo_3/Captura_de_tela_de_2022-06-28_15-08-46.png
  prog_concorrente/resumos/assets_resumo_3/Untitled 1.png
  prog_concorrente/resumos/assets_resumo_3/Untitled 2.png
  prog_concorrente/resumos/assets_resumo_3/Untitled.png
  prog_concorrente/resumos/resumo_parte_1.md
  prog_concorrente/resumos/resumo_parte_2.md
  prog_concorrente/resumos/resumo_parte_3.md
  prog_concorrente/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#502 Update extras.md
  so/extras.md
Labels: hacktoberfest, hacktoberfest-accepted

#506 Update README.md
  tc/leites/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#503 Adiciona atualização de informações e links sobre IA
  ia/linksUteis.md
  ia/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#504 Cria repositório para a disciplina transformação digital
  td/README.md
  td/dificuldadesComuns.md
  td/extras.md
  td/linksUteis.md
  td/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#508 correcao ortografica no readme do tamburetei
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#509 correcao ortografica no codigo de conduta open dev ufcg
  CODE_OF_CONDUCT.md
Labels: hacktoberfest, hacktoberfest-accepted

#510 correcao ortografica no em dica de engenharia de software
  es/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#511 correcao ortografica em ementa de cadeira ATAL
  atal/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#512 Adicionando novas questões do URI (Beecrowd) na pasta de p1
  prog1/implementacoes/uri/1148.cpp
  prog1/implementacoes/uri/1764.cpp
  prog1/implementacoes/uri/2459.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#507 adding proofs of ai
  ia/leites/20212/miniprova1.md
  ia/leites/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#513 ajustando formatação de links
  ia/leites/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#514 Create MatrizCofatores.md
  linear/Assuntos/MatrizCofatores.md
Labels: hacktoberfest, hacktoberfest-accepted

#515 Create RegraCrammer.md
  linear/Assuntos/RegraCrammer.md
Labels: hacktoberfest, hacktoberfest-accepted

#516 Adiciona Programação para Web
  README.md
  progweb/README.md
  progweb/dificuldadesComuns.md
  progweb/extras.md
  progweb/implementacoes/README.MD
  progweb/leites/README.md
  progweb/linksUteis.md
  progweb/resumos/README.md
  progweb/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#517 Adicionando cadeira percepção computacional
  percepcao/README.md
  percepcao/dificuldadesComuns.md
  percepcao/extras.md
  percepcao/linksUteis.md
  percepcao/resumos/introducaoAoConceitoDePercepcao.md
  percepcao/resumos/principiosDeGestalt.md
  percepcao/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#529 adiciona link para tradutor RISC-V
  loac/linksUteis.md
Labels: hacktoberfest, hacktoberfest-accepted

#530 EDA: implementações em Java
  eda/implementacoes/implementacoesJava/EDA/BuscaBinariaRecursiva.java
  eda/implementacoes/implementacoesJava/EDA/ElementosDuplicados.java
  eda/implementacoes/implementacoesJava/EDA/InsereOrdenadoUltimo.java
  eda/implementacoes/implementacoesJava/EDA/InsertionSortRecursivo.java
  eda/implementacoes/implementacoesJava/EDA/SelectionRecursivo.java
  eda/implementacoes/implementacoesJava/EDA/TeoremaDoMestre.java
Labels: hacktoberfest, hacktoberfest-accepted

#533 Adiciona links em Git e Diagramas
  prog2/linksUteis.md
Labels: hacktoberfest, hacktoberfest-accepted

#535 Adiciona visão geral e dicas a PSoft
  psoft/visaoGeralEDicas.md
Labels: hacktoberfest, hacktoberfest-accepted

#536 Adiciona dificuldades comuns a psoft
  psoft/dificuldadesComuns.md
Labels: hacktoberfest, hacktoberfest-accepted

#537 Link de Ebook para iniciantes que desejam se aprofundar em Logica de …
  logica/linksUteis.md
Labels: hacktoberfest, hacktoberfest-accepted

#538 Create Aplicacao.md
  linear/Assuntos/Aplicacao.md
Labels: hacktoberfest, hacktoberfest-accepted

#539 Create Wronskiano.md
  linear/Assuntos/Wronskiano.md
Labels: hacktoberfest, hacktoberfest-accepted

#564 Muda link p1 e adiciona novo link
  prog1/linksUteis.md
Labels: hacktoberfest

#565 Adiciona um livro de apoio para Cálculo 1
  calculo1/linksUteis.md
Labels: hacktoberfest-accepted
